### ISSUE TITLE
Error with simple_json package

### ISSUE THREAD

**Issue by britg** [jsmits/github-cli#26]
I am not sure if this is a ghi thing or simple_json thing ( not familiar with the python world ).  It appears that ghi is installed correctly, but when the setup script attempts to get simple_json, I receive the following error.

I am OSX 10.5.7 and installing through a cloned repo:

Installed /Library/Python/2.5/site-packages/github_cli-0.2.5.2-py2.5.egg
Processing dependencies for github-cli==0.2.5.2
Searching for simplejson
Reading http://pypi.python.org/simple/simplejson/
Reading http://undefined.org/python/#simplejson
Best match: simplejson 2.0.9
Downloading http://pypi.python.org/packages/source/s/simplejson/simplejson-2.0.9.tar.gz#md5=af5e67a39ca3408563411d357e6d5e47
Processing simplejson-2.0.9.tar.gz
Running simplejson-2.0.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wZawJb/simplejson-2.0.9/egg-dist-tmp-eeZcvv
No eggs found in /tmp/easy_install-wZawJb/simplejson-2.0.9/egg-dist-tmp-eeZcvv (setup script problem?)
error: Could not find required distribution simplejson

**Comment by jsmits** [comment]
Unfortunately, this is a known and afaik yet unresolved issue between simplejson and setuptools that pops up every now and then, see for example: http://groups.google.com/group/windmill-dev/browse_thread/thread/908b691f09439c7e 
Probably, you can 'solve' this by manually installing simplejson and then installing github-cli.
