### ISSUE TITLE
configurable authentication source

### ISSUE THREAD

**Issue by FND** [jsmits/github-cli#28]
Since my ~/.gitconfig is [public](http://github.com/FND/homedir), I cannot add my GitHub API token to it.

It would be useful to have an option for specifying username and token elsewhere.

Due to similar requirements, defunkt's gist script allows a custom extraction command to be configured:
http://github.com/defunkt/gist/compare/51c1af83da158aebba2aa6d402557f8ebef44373...713763d2c8fc276a7e083947e589f7683ba8e0e7

**Comment by FND** [comment]
FWIW, I'm reading credentials from ~/.githubconfig as a temporary(?) workaround:
http://github.com/FND/github-cli/commit/1b31bb12183443e4845e2bba364d90bd2d382e75

**Comment by jsmits** [comment]
I figure this could be a nice enhancement. Though I'm not quite sure how defunkt's method works. I looked at his code briefly, but I haven't figured out yet where to put the `token` line he suggests for the Mac OS X Keychain method. It looks to me that the parsing is done in the `str_to_bool` method, but how does it get there? Maybe I have overlooked something, but I'd be happy to add a configurable authentication source, if you can explain how defunkt's method works from a user perspective or give me example code of what you want in `github-cli`.

**Comment by FND** [comment]
I don't actually use defunkt's script [anymore](http://github.com/FND/misc/blob/master/gist), so I'm not sure how this (recent) change works in practice.

However, I could imagine two solutions here:
- command line options - this makes input very flexible (e.g. I might have an alias for `ghi --username `head -n1 ~/.githubconfig` --token `tail -n1 ~/.githubconfig``)
- a configuration file (`~/.githubrc`?) containing the respective commands to be executed (`<key>=<command>`), defaulting to the current use of `git config --global github.<key>`

(I believe the latter is similar to what _gist_ does)

**Comment by jsmits** [comment]
Thanks, that clarifies it for me. When considering new feature requests, I always look whether the suggested feature is useful for the majority of users, simple from a user perspective, easy to remember and esthetically pleasing. To be honest, I think your first suggestion is indeed very flexible, but does not meet the mentioned criteria. I think your second suggestion is a workaround for a use case that is not too common: a public ~/.gitconfig. I believe the easiest solution for your problem would be to make your ~/.gitconfig private.

**Comment by FND** [comment]
Sounds reasonable to me. I'm happy maintaining my little fork for personal use - merging upstream changes should be trivial.

Having said that...

> your first suggestion is indeed very flexible, but does not meet the mentioned criteria

Sounds like my example there was unhelpful.
Consider common *nix tools like [cURL](http://curl.haxx.se), which often have options for passing in username/password - that seems like a fairly generic requirement which also applies to _ghi_ (e.g. `ghi --user <username>:<token>`)?

**Comment by jsmits** [comment]
I like the syntax of this; what I don't like is what the length of the commands will be. I designed the user interface specifically to be short, so it can be used with as little keystrokes as possible. As far as I can imagine right now, the only use case is the public ~/.gitconfig. For me, that does not justify the feature. However, if there are more people who want/need this functionality and/or have other use cases, I'll consider implementing it. For this purpose, I intend to keep this issue open for a while.
