### ISSUE TITLE
Non-ascii encoding

### ISSUE THREAD

**Issue by veged** [jsmits/github-cli#35]
First run for repo with issues with russian chars (например вот так) process error:
`error: 'ascii' codec can't encode characters in position 7-17: ordinal not in range(128)`

**Comment by jsmits** [comment]
I will look into it. Could you show the issue (here) or paste it somewhere? That way it will be easier for me to test it.

**Comment by veged** [comment]
add some to this issue
плюс сюда

**Comment by jsmits** [comment]
Thanks. It should be fixed now, see [here](http://github.com/jsmits/github-cli/commit/c555e5ca61eb3dda4a68c3e0dde5f1689b0a4425/)
Could you try it out?

**Comment by veged** [comment]
easy_install --upgrade github-cli
/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Pyrex/Compiler/Errors.py:17: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  self.message = message
Searching for github-cli
Reading http://pypi.python.org/simple/github-cli/
Reading http://github.com/jsmits/github-cli
Reading http://packages.python.org/github-cli
Reading http://jsmits.github.com/github-cli
Best match: github-cli 0.2.8
Processing github_cli-0.2.8-py2.6.egg
github-cli 0.2.8 is already the active version in easy-install.pth
Installing ghi script to /usr/local/bin

Using /Library/Python/2.6/site-packages/github_cli-0.2.8-py2.6.egg
Processing dependencies for github-cli
Finished processing dependencies for github-cli

and after that: `ghi -V
ghi 0.2.8`

**Comment by jsmits** [comment]
Please try again. It should install now as version 0.2.9 with the updated code.

**Comment by veged** [comment]
cool, looks working now
i don't know is it related to strings encoding, but some issues in `ghi list` is truncated:
example:
   ghi -r veged/shmakowiki
   # open issues on veged/shmakowiki
    1. Списки начинающиеся с более вложенного 
    2. Текст внутри элемента списка после влож
    3. Приведение к "каноническому" виду
    4. Инлайновые расширения

compare with issue #2 in full view:
    ghi -r veged/shmakowiki show 2
     2. Текст внутри элемента списка после
     влож[CUT IN LIST]енного списка
     -------------------------------------------------------------------------------

**Comment by jsmits** [comment]
You're right. List view is truncated, on purpose, to keep one issue per line. Maximum length is 79 for titles in list view. Unfortunately, russian characters are encoded by 2 bytes instead of 1. So, for example, the length of the `2. Текст внутри элемента списка после влож` bytestring is 76, while the actual displayed length is only 42. I'm not sure how to fix this, but I'll look into it.

**Comment by veged** [comment]
maybe possible truncate by "chars", not by "bytes"...
