### ISSUE TITLE
HTTP Error 201: Created (python 2.5 bug)

### ISSUE THREAD

**Issue by trq** [jsmits/github-cli#38]
Getting this message every time a new issue is created. (The issue is still created successfully)

I forked github-cli to see if I could have a look at it, but didn't have much luck. Care to take a look?

I'm assuming that opener.open() throws an exception if it receives anything but a 200 response. I'm not sure if the API has changed or something but successfully creating a new resource (an Issue) returns a 201 Created HTTP status.

**Comment by jsmits** [comment]
Thanks for reporting. Unfortunately, I can't reproduce this. I did a fresh install of github-cli and created an issue from it and it works just fine. I ran the test suite again to make sure I didn't miss something, but the tests are all ok. 
Maybe, it's got something to do with the system you're on. What OS and Python version are you using?

**Comment by trq** [comment]
Sorry, I should have provided that info.

I'm using Debian Lenny, and running 2.5.2 version of Python.

**Comment by jsmits** [comment]
What does the response look like after creation? Does it throw a Python exception? HTTP 201 Created response code is not wrong in itself, I guess.

**Comment by trq** [comment]
It's this piece of code here...

```
try:
    return opener.open(Request(url, data, headers))
except urllib2.HTTPError, info:
    raise Exception("server problem (%s)" % info)
except urllib2.URLError:
    raise Exception("connection problem")
```

It's also happening when I comment on an issue. Here is the output.

thorpe@ob2[~/src/proem]+ ghi comment 6
error: server problem (HTTP Error 201: Created)
thorpe@ob2[~/src/proem]+

**Comment by jsmits** [comment]
I could reproduce it here with python 2.5.4. Apparently, it's a [known](http://comments.gmane.org/gmane.comp.lang.jython.user/8192) bug in python 2.5. Seems like I would have to replace the default urllib2.HttpErrorProcessor, since it only accepts 200 and 206 as valid status codes in the 200 range. Could take a while though. In the meantime, would it be possible for you to upgrade to python 2.6 or (even better) 2.7?

**Comment by trq** [comment]
That is a shame.

There is no way to reliably install > 2.5 on Debian Lenny, which is unfortunately the latest stable version of Debian.

**Comment by jsmits** [comment]
That's unfortunate indeed. On the other hand, github-cli is functional on Python 2.5 as it is right now, only you'll get these annoying (and false) error messages.
