### ISSUE TITLE
Starting ghi without github configuration present will break terminal

### ISSUE THREAD

**Issue by dietmarw** [jsmits/github-cli#39]
When starting ghi without having had `github.user` _and_ `github.token` defined will break the terminal emulation. What happens is that ghi exits silently on `tilda 0.9.6` and will leave the terminal unusable (has to be killed). On xterm it will at least display the error message about missing configuration but will also leave the terminal unusable.

Version: 0.3.0 (and 0.2.7)
System: Ubuntu 10.10 (32bit)

**Comment by jsmits** [comment]
Thanks for the report, I'll look into that.

Regards,
Sander.

**Comment by sc68cal** [comment]
Pretty much any error or abnormal termination blows away the terminal. Input is still accepted, but keystrokes are not echoed back.

$uname -a 
Darwin Uller.local 10.6.0 Darwin Kernel Version 10.6.0: Wed Nov 10 18:11:58 PST 2010; root:xnu-1504.9.26~3/RELEASE_X86_64 x86_64

$ python --version 
Python 2.6.6

**Comment by jsmits** [comment]
Thanks sc68cal for fixing this issue: commit b8183696201fc0da47f6890bebef3fdd0170b347 .
