### ISSUE TITLE
Multiline content on the command line

### ISSUE THREAD

**Issue by dataink** [jsmits/github-cli#42]
This doesn't seem to work for the `-m` argument. :

```
ghi o -m <<EOF
This is the title
This is the body.
This is another line in the body.
EOF
```

I think it would be nicer to able to do this as opposed to a hard `\n` on the command line or opening the editor.

**Comment by jsmits** [comment]
I agree, that would be nicer. I searched around and experimented a little, but haven't found a way to implement this properly (i.e. without losing the existing functionality). I could try harder probably, but in the meantime, if you (or anybody else) have an idea on how to implement this and would like to help, please do.

**Comment by ghuntley** [comment]
That would be much nicer.

**Comment by Mayeu** [comment]
To implement this don't you need to make -m waiting for stdin if no string are provided ?

**Comment by jsmits** [comment]
If you know how to implement this, please do, you're more than welcome to contribute.

**Comment by Mayeu** [comment]
I took a look in the code, it seems that using Optparse and not argparse maybe a problem to implement this.
I can't promise you anything but I'll take a deeper look in this :)
