### ISSUE TITLE
add support to chain the addition/removal of multiple labels to issues

### ISSUE THREAD

**Issue by ghuntley** [jsmits/github-cli#46]
```
› ghi label add api security 20
error: label() takes at most 4 arguments (5 given)

› ghi label add api,security 20
error: server problem (HTTP Error 422: Unprocessable Entity)

› ghi label add security 20    
labels for issue #20:
- security

› ghi label add api 20     
labels for issue #20:
- api
- security
```

**Comment by jsmits** [comment]
Not sure about which UI to use for this. I had the same problem when "designing" the label UIs, namely: labels in github can contain spaces. I accepted this "flaw" in the UI and so far nobody complained about it. But now, this problem pops up in your first example: should it be regarded as one label ('api security') or as two ('api' and 'security'). Parsing the args in your second example could be even more complex, when there are labels with spaces involved. What do you think? Any suggestions on how to handle this properly?

**Comment by ghuntley** [comment]
Issues separated by commas, whitespace enclosed with "/' or escaped out as per standard unix shell conventions?

i.e.

```
$ ghi label add api,securtiy,"user interface"
```

That would all passed through as one {arg}

**Comment by jsmits** [comment]
Of course ;-) Looks fine to me. I don't have time to implement it myself at the moment, would you care to do it?
