### ISSUE TITLE
v3 Support

### ISSUE THREAD

**Issue by paddycarver** [jsmits/github-cli#47]
Github Issues really became useful to me with v3 (Milestones, etc.) I would love to see support for listing Milestones, filtering by Milestone, etc. Any chance of this happening in the future?

**Comment by jsmits** [comment]
Sure, but for now the API v3 is still in a beta state. Also, some of the desired features like searching or filtering by milestone are not described (yet). So when the API v3 comes out of beta, we can start working on it. Any help is welcome.

**Comment by chibicode** [comment]
Searching for a milestone is not described, but filtering http://developer.github.com/v3/issues/ and listing http://developer.github.com/v3/issues/milestones/ seem to be listed now. It'd be great to see this on github-cli.

**Comment by nijikokun** [comment]
v2 is being phased out on May 1st. Better update soon.

**Comment by jsmits** [comment]
Thanks for the notice. I'm afraid I won't be able to update to v3 myself, but I'm open to pull requests regarding this issue. Contributors will of course be added to the authors list.

**Comment by jsmits** [comment]
I'm closing this issue now. A possible alternative for github-cli that addresses API v3 is Stephen Celis'  [ghi](https://github.com/stephencelis/ghi/).
