### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by pazz** [jsmits/github-cli#50]
```
$ python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from github.version import get_version
ImportError: No module named version
pazz@megatron:~/projects/github-cli$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from github.version import get_version
ImportError: No module named version
```

the same error occurs when i do a `pip install github-cli`.
I'm on ubuntu 11.04.

**Comment by jsmits** [comment]
that's strange, are you sure the whole source tree is in your ~/projects/github-cli folder?
I mean, is the src/github folder available, with the version.py module?

**Comment by pazz** [comment]
yes, its all there. its a fresh git checkout. i _might_ have to do with soem other tools i tried before, and that clutter my path..
let me check.

**Comment by pazz** [comment]
ah :) thats it. there is a tool called "github-tools" which also uses the github namespace and was installed.

```
Finished processing dependencies for github-cli==1.0.0
```

thanks anyway!

**Comment by jsmits** [comment]
ok, no problem, glad that you found the cause
